### 넘파이 ndarray

n-d array를 생성하는방법은? 리스트를 넣어주면된다.

In [2]:
import numpy as np

In [3]:
list1 = [1, 2, 3]
print("list 1: " ,list1)
print("list의 타입은 : " ,type(list1))

array1 = np.array(list1)
print("array1:", array1)
print("array1 type:" ,type(array1))

list 1:  [1, 2, 3]
list의 타입은 :  <class 'list'>
array1: [1 2 3]
array1 type: <class 'numpy.ndarray'>


다음과 같이 `list`의 타입은 `list`
array1의 타입은 `numpy.ndarray`로 ndarray가 되는 것을 볼 수 있다

In [4]:
D1Array = np.array([1,2,3])
print("D1Array의 타입 : ", type(D1Array))
print("D1Array의 형태 : ", D1Array.shape)

D2Array = np.array([[1,2,3],
                   [2,3,4]])
print("D2Array의 타입 : ", type(D2Array))
print("D2Array의 형태 : ", D2Array.shape)

D3Array = np.array([[1,2,3]])
print("D3Array의 타입 : ", type(D3Array))
print("D3Array의 형태 : ", D3Array.shape)

D1Array의 타입 :  <class 'numpy.ndarray'>
D1Array의 형태 :  (3,)
D2Array의 타입 :  <class 'numpy.ndarray'>
D2Array의 형태 :  (2, 3)
D3Array의 타입 :  <class 'numpy.ndarray'>
D3Array의 형태 :  (1, 3)


### 차원을 확인해보자
확인을 해보았을 때 `[[]]`에 대해서는 2차원 배열 취급을 한다. 결론적으로 한번더 확인해보면 다음과 같다

In [5]:
print('D1array {:0}, D2array {:1}, D3array {:2} '.format(D1Array.ndim, D2Array.ndim, D3Array.ndim))

D1array 1, D2array 2, D3array  2 


### data 값 타입 확인해보기
`dtype`이라는 함수를 통해서 확인할 수 있다.

In [6]:
list1 = [1,2,3]
print(type[list1])
array1 = np.array(list1)

print(type(array1))
print(array1, array1.dtype)

type[[1, 2, 3]]
<class 'numpy.ndarray'>
[1 2 3] int64


### data의 형변환 2
만약 list에 정수와 문자열이 섞여있다면 이는 -> **문자열**의 값으로 모두 변환된다
정수와 실수의 경우에도 -> **실수**로 자동으로 형변환이 된다.
다음 코드를 통해서 살펴보도록하자

In [7]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


### `astype()`을 통한 명시적 형변환
`astype()`을 사용해서 명시적으로 형변환을 할 수 있다.

In [8]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1,2.2,3.3])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


### Axis 기반의 연산함수 수행
numpy에서는 `axis`기반으로 연산을 할 수 있다.

In [9]:
array2 = np.array([[1,2,3],
                   [2,3,4]])
print(array2.sum())
print(array2.sum(axis=0))
print(array2.sum(axis=1))

15
[3 5 7]
[6 9]


### ndarray를 편리하게 생성 후 초기화
방법은 `arange`, `zeros`, `ones`로 3개가 존재한다.
`arrange`는 10을 입력하면 0~9으로
`zero`는 모두 0으로
`ones`는 모두 1로이다.

In [10]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [11]:
zero_array = np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [12]:
one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### ndArray의 shape를 변경하는 방법
다음과 같이 `reshape()` 메서드를 사용한다

In [13]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [14]:
# 만약 변환할 수 없는 shape 구조를 입력한다면 오류가 발생하게 된다!!
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

### `reshape()`에 `-1`이 부여되는 경우?
`-1`이 부여된다면 고정된 가변적인 ndarray형태로 변환된다. 다음예제를 살펴보자

In [ ]:
array1 = np.arange(10)
print(array1)

#만약 axis 0에 -1을 넣으면 ? 키기는 axis 1에 고정하고 axis 0은 알아서 할당된다
array2 = array1.reshape(-1,5)
print('array2 shape : ', array2.shape)
print('array2:\n', array2)

# axis 1에 -1이 있으면 axis 0의 크기는 입력한 값에 고정하고 axis 1의 크기는 알아서 할당
array3 = array1.reshape(5, -1)
print('array3 shape : ', array3.shape)
print('array3 : \n' , array3)

### `reshape()`를 사용할 떄 차원을 고정해야할 경우
`-1`을 활용하여 1차원 배열 2차원 배열 n차원 배열로 고정할 수 있다.

In [ ]:
# 1차원 ndarray를 2차원 or 2차원 ndarray를 1차원으로 변환할 때 사용하는 법
array1 = np.arange(5)

# 1차원 ndarray를 2차원으로 변환 / 이 떄의 axis1의 크기는 반드시 1이여야 한다.
array2d_1 = array1.reshape(-1, 1)
print("array2d_1 shape : ", array2d_1.shape)
print("array2d_1 : \n" , array2d_1)

# 2차원 ndarray를 1차원으로 변환시키기!!
array1d = array1.reshape(-1,)
print("array1d shape :", array1d.shape)
print("array1d:\n", array1d)

In [ ]:
# 안되는 것을 억지로 요구할 경우
array1 = np.arange(10)
array4 = array1.reshape(-1,4)

# 어떤 짓을 해도 2차원으로 변형할 때 2개의 원소가 남는다 -> 오류발생

In [ ]:
# 또한, -1 값은 반드시 1개의 인자만 입력할 수 있다 (-1,-1)은 안된다
array1.reshape(-1,-1)

## 넘파이의 `ndarray`의 데이터 세트 선택하기 (인덱싱)
넘파이에서 ndarray의 일부 데이터 세트 or 특정 데이터만 선택할 수 있도록 하는 인덱싱에 대해 알아보려합니다/

### 단일 값 추출
한 개의 데이터만 추출하는 방법을 알아보려고 합니다.
다음 같이 해당하는 위치의 인덱스 값을 `[]`안에 입력하면 됩니다.

In [15]:
# 1~9까지 1-D array를 생성한다.
array1 = np.arange(start=1, stop=10)
print('array1 :', array1)

# 인덱싱을 통해서 단일 값 추출
value = array1[2]
print('value : ', value)
print(type(value))

array1 : [1 2 3 4 5 6 7 8 9]
value :  3
<class 'numpy.int64'>


또한, **음수** 값을 사용하여 뒤의 값을 바로 추출할 수도 있습니다.

In [16]:
print("맨 뒤의 값 : \n", array1[-1])
print("맨 뒤에서 두 번째 값 : \n", array1[-2])

맨 뒤의 값 : 
 9
맨 뒤에서 두 번째 값 : 
 8


이러한 값들을 통해서 해당 인덱스에 접근하여 값을 **변경할 수 도** 있습니다.

In [17]:
# 0번째 index의 값 변경하기
array1[0] = 9
print("array1 : ", array1)

array1 :  [9 2 3 4 5 6 7 8 9]


다차원에서의 단일 값을 추출하는 방법은 다음과 같습니다.

만약, 2차원이라면 행과 열의 값을 `[]`안에 넣어주면 됩니다.

In [21]:
Tarray1d = np.arange(start=1, stop=10)
print(Tarray1d)
array2d = Tarray1d.reshape(3,3)
print(array2d)

print("(row = 0, column = 0) index가 가리키는 값은 : ", array2d[0, 0])
print("(row = 1, column = 2) index가 가리키는 값은 : ", array2d[1, 2])
print("(row = 0, column = 2) index가 가리키는 값은 : ", array2d[0, 2])
print("(row = 2, column = 2) index가 가리키는 값은 : ", array2d[2, 2])

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row = 0, column = 0) index가 가리키는 값은 :  1
(row = 1, column = 2) index가 가리키는 값은 :  6
(row = 0, column = 2) index가 가리키는 값은 :  3
(row = 2, column = 2) index가 가리키는 값은 :  9


### 슬라이싱
`:` 기호를 이용해서 연속한 데이터를 슬라이싱해서 추출이 가능합니다.

In [22]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


`:` 기호 앞 뒤의 값은 생략할 수 있습니다.
- `:` 기호 앞의 시작 인덱스를 생략한다면 맨 처음 인덱스인 0으로 간주합니다.
- `:` 기호 뒤에 종료 인덱스를 생략한다면 맨 마지막 인덱스로 간주합니다.
- `:` 기호 앞/뒤를 모두 생략하면 맨 처음부터 맨 마지막 인덱스로 간주합니다

In [24]:
array1 = np.arange(start=1, stop=10)

# 시작 인덱스 생량
array4 = array1[:3]
print(array4)

# 종료 인덱스 생략
array5 = array1[3:]
print(array4)

# 둘다 생량
array6 = array1[:]
print(array6)

[1 2 3]
[1 2 3]
[1 2 3 4 5 6 7 8 9]


### 2차원에서 슬라이싱 사용하기
2차원에서 슬라이싱을 사용하는 것은 1차원이랑 동일하다

예제를 보면서 바로 이해해보자

In [25]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)

# 모든 경우의 슬라이싱
print("array[0:2, 0:1] : \n", array2d[0:2, 0:1])
print("array[1:3, 0:3] : \n", array2d[1:3, 0:3])
print("array[1:3, :] : \n", array2d[1:3, :])
print("array[:, :] : \n", array2d[:, :])
print("array[:2, 1:] : \n", array2d[:2, 1:])
print("array[:2, 0] : \n", array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array[0:2, 0:1] : 
 [[1]
 [4]]
array[1:3, 0:3] : 
 [[4 5 6]
 [7 8 9]]
array[1:3, :] : 
 [[4 5 6]
 [7 8 9]]
array[:, :] : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array[:2, 1:] : 
 [[2 3]
 [5 6]]
array[:2, 0] : 
 [1 4]


In [26]:
# 2차원 array에서 뒤에 오는 인덱스를 지웠을 경우
print(array2d[0])
print(array2d[1])

#출력해보면 axis0이 최대값을로 고정되어 있는 것을 볼 수 있다.
print('array2d[0] shape: ',array2d[0].shape,'array2d[1] shape: ',array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape:  (3,) array2d[1] shape:  (3,)


### 팬시 인덱싱
팬시 인덱싱은 List나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방법입닌다.

In [27]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1], 2]
print('array2d[[0,1], 2] =>', array3.tolist() )

array4 = array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2] =>', array4.tolist() )

array5 = array2d[[0,1], 2]
print('array2d[[0,1]] =>', array5.tolist() )

array2d[[0,1], 2] => [3, 6]
array2d[[0,1], 0:2] => [[1, 2], [4, 5]]
array2d[[0,1]] => [3, 6]


### 불린 인덱싱
조건 필터링과 검색을 동시에 할 수 있기 때ㅜㄴ에 매우 자주 사용되는 인덱싱 방식입니다.

예를들어서 1차원 ndarray에서 5보다 큰 데이터만 추출해라 처럼 이런식으로 비교를 통해 추출하는 방식입니다

In [28]:
array1d = np.arange(start=1, stop=10)

# 5보다 큰 값만 추출
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱의 결과 값 : ', array3)

array1d > 5 불린 인덱싱의 결과 값 :  [6 7 8 9]


In [30]:
# array1d > 5만 입력하면 불리언으로 반환되는 리스트 값을 반환합니다
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [32]:
# 위와 같은 행렬처럼 역의 방식도 성립하는지 확인해 봅시다.
boolean_index = np.array([False,False,False,False,False,True,True,True,True])
array3 = array1d[boolean_index]

print('불린 인덱스로 필터링 한 결과 : ',array3)

불린 인덱스로 필터링 한 결과 :  [6 7 8 9]


## 행렬의 정렬 - `sort()`와 `argsort()`

### 행렬 정렬
넘파이에서의 행렬을 정렬하는 방법은 2가지가 있습니다.
1. `np.sort()`처럼 `sort()`를 호출하는 방식
2. `ndarray.sort()`와 같이 행렬 자체에서 `sort()`를 호출하는 방식입니다.

`np.sort()`는 원 행렬은 그대로 유지한 채 원 행렬에서 **정렬된 행렬을 반환합니다.**

`ndarray.sort()`는 원 행렬 자체를 정렬한 형태로 변환합니다.

반환 값은 `None`을 가집니다.

In [33]:
org_array = np.array([3,1,9,5])
print("원본 행렬 출력 : ",org_array)

#np.sort()로 정렬하는 방법
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬: ', sort_array1)
print("정렬 후 원본 행렬 :", org_array)

#ndarray.sort()로 정렬하기
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬 : ', sort_array2)
print('org_array.sort() 후 원본 행렬 :', org_array)

원본 행렬 출력 :  [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬:  [1 3 5 9]
정렬 후 원본 행렬 : [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬 :  None
org_array.sort() 후 원본 행렬 : [1 3 5 9]


In [34]:
# 내림차순으로 정렬하는 방법
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬 :', sort_array1_desc)

내림차순으로 정렬 : [9 5 3 1]


내림차순으로 진행하려면 `[::-1]`을 사용하면 된다.

### 2차원 배열에서의 정렬
axis 축 값 설정을 통해서 row방향인지 column방향인지 정렬을 수행할 수 있습니다.

In [35]:
array2d = np.array([[8,12],
                    [7,1]])

# row 방향으로 정렬하는 법
sort_array2d_axis0 = np.sort(array2d, axis=0)
print('row 방향으로 정렬 : ', sort_array2d_axis0)

# column 방향으로 정렬하는 법
sort_array2d_axis1 = np.sort(array2d, axis=1)
print('column 방향으로 정렬 : ', sort_array2d_axis1)

row 방향으로 정렬 :  [[ 7  1]
 [ 8 12]]
column 방향으로 정렬 :  [[ 8 12]
 [ 1  7]]


### 정렬된 행렬의 인덱스를 반환하기
원본 행렬이 정렬되었을 때 **기존 원본 행렬의 원소에 대한 인덱스**가 필요할 떄가 있다.

`np.argsort()`를 이용하면 정렬 행렬의 원본 행렬 인덱스를 ndarray형으로 반환해서 줍니다.

In [36]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)

print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스는 : ', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스는 :  [1 0 3 2]


In [37]:
# 내림 차순일 때도 동일하다.
org_array = np.array([3,1,9,5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스는 : ', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스는 :  [2 3 0 1]


### 많이 사용되는 예시
`argsort()`는 넘파이에서 매우 활용도가 높다고 합니다.

예시로 학생별 시험 성적을 데이터로 표현하기 위해서는 학생의 이름, 시험 성적을 ndarray로 각각 가져야 합니다.

학생의 이름, 시험 성적을 가졌을 때 시험 성적을 토대로 정렬을 하면 누구의 점수인지 확인을 할 수 없습니다.

이때 인덱스를 저장해서 팬시 인덱스로 적용해서 사용을 합니다.

In [38]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Haechan', 'Baegopa','Babjo'])
score_array = np.array([78,95,84,98,88])

sort_indices_asc = np.argsort(score_array)
print('성적을 오름차순으로 정렬할 때의 index 값 :',sort_indices_asc)
print('성적을 오름차순으로 정ㄹ려할 떄의 nameArray를 출력하는 방법 :' , name_array[sort_indices_asc])

성적을 오름차순으로 정렬할 때의 index 값 : [0 2 4 1 3]
성적을 오름차순으로 정ㄹ려할 떄의 nameArray를 출력하는 방법 : ['John' 'Haechan' 'Babjo' 'Mike' 'Baegopa']


# 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

### 행렬 내적(행렬 곱)
이러한 행렬의 내적은 `np.dot()`을 통해서 계산이 가능합니다.

In [39]:
A = np.array([[1,2,3],
             [4,5,6]])
B = np.array([[7,8],
              [9,10],
              [11,12]])

dot_product = np.dot(A, B)
print('행렬의 내적결과 \n', dot_product)

행렬의 내적결과 
 [[ 58  64]
 [139 154]]


### 전치행렬
원 행렬에서 행과 열 위치를 교환한 원소로 구성된 행렬을 전치행렬이라고 합니다.

이는 `transpose()`를 통해서 쉽게 구할 수 있습니다.

In [40]:
A = np.array([[1,2],
              [3,4]])

transpose_mat = np.transpose(A)
print('A의 전치 행렬은 : \n',transpose_mat)

A의 전치 행렬은 : 
 [[1 3]
 [2 4]]
